Another massive clean-up
Re-write practically everything in Bash
Add testsuite (again, for real this time)
Re-work and re-write rtai-load entirely (much simpler now)
Silence annoying warning in fifos.c
BASH EVERYWHERE!
Delete more stuff we don't need/use
Further Kconfig clean-ups
Change permission modes on some files
Drop out-dated kernel config files

Signed-off-by: Alec Ari <alec@onelabs.com>

diff --git a/base/arch/x86/calibration/setsmi.in b/base/arch/x86/calibration/setsmi.in
--- a/base/arch/x86/calibration/setsmi.in
+++ b/base/arch/x86/calibration/setsmi.in
@@ -1,17 +1,36 @@
 #!/usr/bin/env bash
 # Re-written in GNU Bash by Alec Ari
 
+if [[ "${EUID}" != 0 ]] ; then
+	echo "This script must be run with superuser permissions."
+	exit 1
+fi
+
 while [[ $# -gt 0 ]] ; do
 argument="$1"
-case ${argument} in
+case "${argument}" in
 	hal_smi_masked_bits)
-	shift
 	;;
 	*)
 	;;
 esac
 shift
 done
+
+# Determine if setting or resetting
+CMDNAME=$(basename "${0}")
+case "${CMDNAME}" in
+	setsmi)
+		SMIRESET="0"
+		;;
+	rstsmi)
+		SMIRESET="1"
+		;;
+	*)
+		echo "invalid SMI script name ${0}"
+		exit 1
+		;;
+esac
 
 if [[ -n "${argument}" && "${argument}" == hal_smi_masked_bits=* ]] ; then
 	echo "Using ${argument}"
@@ -21,27 +40,11 @@ fi
 
 MODULENAME="rtai_smi.ko"
 
-# Determine if setting or resetting
-CMDNAME=$(basename "${0}")
-case "${CMDNAME}" in
-	setsmi)
-	SMIRESET="0"
-	;;
-	rstsmi)
-	SMIRESET="1"
-	;;
-	*)
-	echo "invalid SMI script name ${0}"
-	exit 1
-	;;
-esac
-
-if [[ "${EUID}" != 0 ]] ; then
-	echo "This script must be run with superuser permissions."
-	exit 1
-fi
-
-type rtai-config > /dev/null 2>&1 || echo "${CMDNAME} cannot find rtai-config" ; exit 1 ;
+PATH="${PATH}:@prefix@/bin"
+type rtai-config > /dev/null 2>&1 || \
+	{
+	echo "${CMDNAME} cannot find rtai-config" ; exit 1 ;
+	}
 
 MODULEDIR=$(rtai-config --module-dir)
 
diff --git a/base/scripts/bootstrap b/base/scripts/bootstrap
--- a/base/scripts/bootstrap
+++ b/base/scripts/bootstrap
@@ -1,36 +1,43 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-die() {
-	echo
-	echo "error: $1";
-	echo
-}
+echo -e "Running libtoolize..."
+libtoolize --force --copy --automake || \
+	{
+	echo -e "Error running libtoolize" ;
+	exit 1 ;
+	}
+echo -e "Done."
 
-echo
+echo -e "Running aclocal..."
+aclocal --force -I base/scripts/autoconf || \
+	{
+	echo -e "Error running aclocal" ;
+	exit 1 ;
+	}
+echo -e "Done."
 
-echo -n "running libtoolize..."
-libtoolize --force --copy --automake
-if [ "$?" != "0" ]; then die "running libtoolize"; fi
-echo "done"
+echo -e "Running autoconf..."
+autoconf --force || \
+	{
+	echo -e "Error running autoconf" ;
+	exit 1 ;
+	}
+echo -e "Done."
 
-echo -n "running aclocal..."
-aclocal --force -I base/scripts/autoconf
-if [ "$?" != "0" ] ; then die "running aclocal"; fi
-echo "done"
+echo -e "Running autoheader..."
+autoheader --force || \
+	{
+	echo -e "Error running autoheader" ;
+	exit 1 ;
+	}
+echo -e "Done."
 
-echo -n "running autoconf..."
-autoconf --force
-if [ "$?" != "0" ]; then die "running autoconf"; fi
-echo "done"
+echo -e "Running automake..."
+automake --force -a -c || \
+	{
+	echo -e "Error running automake" ;
+	exit 1 ;
+	}
+echo -e "Done.\n"
 
-echo -n "running autoheader..."
-autoheader --force
-if [ "$?" != "0" ]; then die "running autoheader"; fi
-echo "done"
-
-echo -n "running automake..."
-automake --force -a -c
-if [ "$?" != "0" ]; then die "running automake"; fi
-echo "done"
-
-echo
+exit 0
diff --git a/base/scripts/rtai-load.in b/base/scripts/rtai-load.in
--- a/base/scripts/rtai-load.in
+++ b/base/scripts/rtai-load.in
@@ -1,255 +1,71 @@
-#!/bin/sh
-# RTAI application loader script.
-# (Processes the .runinfo files)
-# April 2003, <rpm@xenomai.org>
+#!/usr/bin/env bash
+# RTAI application loader script - Processes the .runinfo files
+# Completely re-written in GNU Bash by Alec Ari
 
-usage='usage: rtai-load [[dir:]target]'
-prefix="@prefix@"
-exec_prefix="@exec_prefix@"
-insmod=/sbin/insmod
-modprobe=/sbin/modprobe
-rmmod=/sbin/rmmod
-verbose=0
-spc=" 	"
-
-if test "x$1" = x--help; then
-  echo $usage
-  exit 0
+if [[ "${EUID}" != 0 ]] ; then
+	echo "This script must be run with superuser permissions."
+	exit 1
 fi
 
-if test "x$1" = x--verbose; then
-  verbose=1
-  shift
-fi
-
-qual_target=$1
-target_dir=`echo $qual_target|cut -d: -f1`
-target_name=`echo $qual_target|cut -s -d: -f2`
-if test "x$target_dir" = x; then
-   target_dir=`pwd`
-fi
-if test "x$target_name" = x; then
-   if `echo $target_dir | grep -q /`; then
-      target_name=default
-   else
-      target_name=$target_dir
-      target_dir=.
-   fi
-fi
-
-run_info_file=$target_dir/.runinfo
-
-if test \! -r $run_info_file; then
-   echo "rtai-load: cannot find run info: $run_info_file"
-   exit 2
-fi
-
-if test $target_name = default; then
-  target_name=`cut -s -d: -f1 $run_info_file | head -1`
-  if test "x$target_name" = x; then
-     echo "rtai-load: no target defined in $run_info_file"
-     exit 2
-  fi
-fi
-
-stanza=`grep "^[$spc]*$target_name[$spc]*:" $run_info_file`
-
-if test "x$stanza" = x; then
-   have_user_command_option=`cut -d: -f1 .runinfo | grep user_command`
-   if test "x$have_user_command_option" = x; then
-       echo "passo di qui"
-       echo "rtai-load: cannot find run info for target $target_name"
-       exit 2
-   else
-       target_name=user_command
-       stanza=`grep "^[$spc]*$target_name[$spc]*:" $run_info_file`
-   fi
-fi
-
-rtai_moddir=`grep "^[$spc]*rtai_moddir[$spc]*=" $run_info_file`
-user_moddir=`grep "^[$spc]*user_moddir[$spc]*=" $run_info_file`
-
-if test "x$rtai_moddir" = x; then
-  eval rtai_moddir='${DESTDIR}@RTAI_MODULE_DIR@'
-else
-  eval $rtai_moddir
-fi
-
-eval $user_moddir
-
-if `$modprobe -nq adeos > /dev/null 2>&1`; then
-   target_deps="adeos+"
-else
-   target_deps=
-fi
-
-target_deps="${target_deps}trace+hal+malloc+`echo $stanza | cut -d: -f2`"
-target_info=`echo $stanza | cut -d: -f3`
-target_mesg=`echo $stanza | cut -s -d: -f4`
-
-if test "$target_name" = user_command; then
-    target_info=`echo $target_info | sed s/";"/" $*\;"/` 
-    shift $#
-fi
-
-test $verbose = 1 && echo "Running $target_name from $run_info_file"
-
-if test \! "x`type -t sudo`" = x; then
-  sudo=sudo
-fi
-
-if test \! "x$target_mesg" = x; then
-  case "$target_mesg" in
-  control_c)
-    target_mesg="Type ^C to stop this application."
-    ;;
-  esac
-  echo "*"
-  echo "*"
-  echo "* $target_mesg"
-  echo "*"
-  echo "*"
-fi
-
-sync
-
-loadlist=`cat /proc/modules | ( \
-  while read lm; do \
-    set -- $lm; \
-    loadlist="$loadlist $1"; \
-  done  ; echo $loadlist )`
-
-( cd $target_dir ;
-
-inslist=""
-children_pids=""
-
-cleanup () {
-
-    if test \! "x$children_pids" = x; then
-#      $sudo kill -SIGINT $children_pids > /dev/null 2>&1 see comment below
-       $sudo kill -INT $children_pids > /dev/null 2>&1
-       children_pids=""
-       sleep 1
-    fi
-    if test \! "x$inslist" = x; then
-       for mod in $inslist ; do
-	  test $verbose = 1 && echo "+ $rmmod $mod"
-	  $sudo $rmmod $mod
-       done
-       inslist=""
-    fi
-}
-
-#trap cleanup SIGINT  this is an old reminder, it seems it must be like below
-trap cleanup INT
-
-while test -n "$target_deps" ; do
-  mod=`echo $target_deps|cut -d+ -f1`
-  target_deps=`echo $target_deps|cut -s -d+ -f2-`
-  if test -h $rtai_moddir/rtai_$mod.ko; then
-     # Substitute the symlink with the target name since
-     # new modutils (>= 2.5.48) will use the actual name.
-     mod=`ls -l $rtai_moddir/rtai_$mod.ko|sed -e "s,.* \-> .*rtai_\([a-z0-9A-Z]*\).ko.*,\1,"`
-  fi
-  if `echo $loadlist | grep -vq "\\brtai_$mod\\b"`; then
-     # If we cannot find the module in our install dir, try Linux's
-     # one. If the latter fails too, assume the feature is built into
-     # the scheduler or not needed. Obviously, we should _always_ find
-     # the scheduler...
-     if test -r $rtai_moddir/rtai_$mod.ko; then
-        test $verbose = 1 && echo "+ $insmod $rtai_moddir/rtai_$mod.ko"
-        $sudo $insmod $rtai_moddir/rtai_$mod.ko
-	if test $? = 0 ; then
-           inslist="rtai_$mod $inslist"
-           loadlist="$loadlist $mod"
-	else
-	   echo "ERROR: cannot load $rtai_moddir/rtai_$mod.ko"
-	   break
-        fi
-     elif `$modprobe -n $mod > /dev/null 2>&1`; then
-        test $verbose = 1 && echo "+ $modprobe $mod"
-        $sudo $modprobe $mod
-        inslist="$mod $inslist"
-        loadlist="$loadlist $mod"
-     fi
-  fi
+while [[ "${#}" -gt 0 ]] ; do
+argument="${1}"
+case "${argument}" in
+	runinfo)
+		;;
+	.runinfo)
+		;;
+	*)
+		echo "Usage: rtai-load [path to .runinfo]"
+		exit 0
+		;;
+	esac
+	shift
 done
 
-while test -n "$target_info" ; do
-  action=`echo $target_info|cut -d';' -f1`
-  target_info=`echo $target_info|cut -s -d';' -f2-`
-  set -- $action
+PATH="${PATH}:@prefix@/bin"
+type rtai-config > /dev/null 2>&1 || \
+	{
+	echo "${CMDNAME} cannot find rtai-config" ; exit 1 ;
+	}
 
-  case "$1" in
+MODULEDIR=$(rtai-config --module-dir)
 
-    push)
+if [[ -n "${argument}" && "${argument}" == *runinfo ]] ; then
+	RUNINFO="${argument}"
+else
+	echo "Incorrect or no command specified."
+	exit 1
+fi
 
-	mod=`basename $2 .ko`
-        if test -r $rtai_moddir/$mod.ko; then
-           modpath="$rtai_moddir/$mod"
-        elif test -r $user_moddir/$mod.ko; then
-           modpath="$user_moddir/$mod"
-        else
-           modpath="$mod"
-        fi
-	if `echo $loadlist | grep -vq "\\b$mod\\b"`; then
-	   test $verbose = 1 && echo "+ $insmod $modpath.ko"
-	   $sudo $insmod $modpath.ko
-	   if test $? = 0; then
-              loadlist="$loadlist $mod"
-	      inslist="$mod $inslist"
-	   else
-	      echo "ERROR: cannot load $modpath.ko"
-	   fi
-	fi
-	;;
+if [[ -r "${RUNINFO}" ]] ; then
+	echo ".runinfo is ${RUNINFO}"
+else
+	echo "Unable to find .runinfo file at ${argument}"
+	exit 1
+fi
 
-    pop)
+for_insmod=$(cat "${RUNINFO}")
+for_rmmod=$(tac "${RUNINFO}")
+LOADED_RTAI_MODULES=$(grep "rtai_" /proc/modules)
 
-	shift
-	if test "x$*" = x; then
-           rmlist=`echo $inslist | cut -s -f1 -d' '`
-        else
-           rmlist=$*
-	fi
-        _inslist="$inslist"
-	if test \! "x$rmlist" = x; then
-           for mod in $rmlist ; do
-	      test $verbose = 1 && echo "+ $rmmod $mod"
-	      $sudo $rmmod $mod && _inslist=`echo $_inslist | sed -e "s,$mod,,g"`
-           done
-        inslist="$_inslist"
-	fi
-	;;
-
-    popall|flush)
-
-        cleanup
-	;;
-
-    *)
-
-        case "$1" in
-	  exec|spawn) shift ;;
-	  klog) set -- \! tail -f /var/log/messages ;;
-	esac
-	e=`echo $* | sed -e "s,^[$spc]*![$spc]*\\(.*\\)$,\\1,"`
-        test "$e" = "$*" && suflag= || suflag=$sudo
-	set -- $e
-	e=`echo $* | sed -e "s,\\(.*\\)&[$spc]*$,\\1,"`
-        test "$e" = "$*" && waitflag=1 || waitflag=0
-	set -- $e
-	test $verbose = 1 && echo "+ spawning command ($*)"
-	if test $waitflag = 1; then
-           $suflag $*
-        else
-           $suflag $* &
-	   children_pids="$! $children_pids"
-	fi
-	;;
-  esac
-
-done )
+if [[ -z "${LOADED_RTAI_MODULES}" ]] ; then
+	echo "No RTAI modules loaded."
+	echo "Running insmod on ${RUNINFO}..."
+	for module in ${for_insmod} ; do
+		insmod "${MODULEDIR}/${module}"
+	done
+else
+	echo "RTAI loaded."
+	echo "Unloading modules..."
+	echo "Running rmmod on ${RUNINFO}..."
+	for module in ${for_rmmod} ; do
+		rmmod "${MODULEDIR}/${module}"
+	done
+	echo "All RTAI modules unloaded."
+	echo "Running insmod on ${RUNINFO}..."
+	for module in ${for_insmod} ; do
+		insmod "${MODULEDIR}/${module}"
+	done
+fi
 
 exit 0
