Initial clean-up (WIP)
Only compile tested so far.

Summary of changes:

1.) Add my name where credit is due

2.) Remove comedi, drivers, serial, rtai-py, rtai-lab, rtdm, bits,
leds, watchdog, usi, tbx, netrpc, and some Xenomai files.

3.) Disable math for now until I plug newlib into this.
4.) Remove C++ support (C++ not supported in kernel)
5.) Remove ARM arch (ancient)

6.) Remove docs (Doxygen and all that is tricky to get working with
this brand new build system)

7.) Re-write configure.ac based off of my old stable one
8.) Remove M68K and other old definitions/conditionals
9.) Clean-up all Makefiles, and revamp the entire build system
10.) Update Kconfig file, defconfig, and update Kconfig itself.
11.) Remove a lot of dead code.
12.) Fix all build/compiling problems.
13.) Fix rtai_defs.h.in and re-work how rtai_defs.h gets generated.
14.) Remove KVM and rtai-sim stuff.
15.) Increase number of CPUs to build for (Ryzen 9 3950X prep)
16.) Remove trace support
17.) Force usage of Kbuild and OLD_FASHIONED

18.) Force MMU, FPU, GENERIC_CLOCK_EVENTS, IO_APIC and TSC support,
run checks on these to make sure the options are enabled.

19.) Modify some RTAI default options

TODO:

Math support using integrated newlib
CONFIG_MODULE re-work (configure.ac)
Drop all #if #else statements for old kernel versions and arches
Update kernel patch to latest 4.14 kernel
Verify that the testsuite works

Remove more #if #else statements and add more checks to configure.ac
such as PROCFS and UDEV support. These should always exist.

Go through everything and test this tree to death.

Signed-off-by: Alec Ari <neotheuser@ymail.com>

diff --git a/base/scripts/bootstrap b/base/scripts/bootstrap
--- a/base/scripts/bootstrap
+++ b/base/scripts/bootstrap
@@ -1,56 +1,43 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# Copyright (C) 2005-2017 The RTAI project
-# This [file] is free software; the RTAI project
-# gives unlimited permission to copy and/or distribute it,
-# with or without modifications, as long as this notice is preserved.
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
-# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
-# PARTICULAR PURPOSE.
+echo -e "Running libtoolize..."
+libtoolize --force --copy --automake || \
+	{
+	echo -e "Error running libtoolize" ;
+	exit 1 ;
+	}
+echo -e "Done."
 
+echo -e "Running aclocal..."
+aclocal --force -I base/scripts/autoconf || \
+	{
+	echo -e "Error running aclocal" ;
+	exit 1 ;
+	}
+echo -e "Done."
 
+echo -e "Running autoconf..."
+autoconf --force || \
+	{
+	echo -e "Error running autoconf" ;
+	exit 1 ;
+	}
+echo -e "Done."
 
-ACLOCAL=aclocal
-AUTOMAKE=automake
+echo -e "Running autoheader..."
+autoheader --force || \
+	{
+	echo -e "Error running autoheader" ;
+	exit 1 ;
+	}
+echo -e "Done."
 
-die() {
-	echo
-	echo "error: $1";
-	echo
-	exit -1;
-}
+echo -e "Running automake..."
+automake --force -a -c || \
+	{
+	echo -e "Error running automake" ;
+	exit 1 ;
+	}
+echo -e "Done.\n"
 
-echo
-
-echo -n "running libtoolize..."
-libtoolize -c --automake
-if [ "$?" != "0" ]; then die "running libtoolize"; fi
-echo "done"
-
-echo -n "running aclocal..."
-if test -r acinclude.m4 ; then
-   touch acinclude.m4
-   $ACLOCAL
-else
-   $ACLOCAL -I base/config/autoconf
-fi
-if [ "$?" != "0" ] ; then die "running aclocal"; fi
-echo "done"
-
-echo -n "running autoconf..."
-autoconf
-if [ "$?" != "0" ]; then die "running autoconf"; fi
-echo "done"
-
-echo -n "running autoheader..."
-autoheader
-if [ "$?" != "0" ]; then die "running autoheader"; fi
-echo "done"
-
-echo -n "running automake..."
-$AUTOMAKE -a -c
-if [ "$?" != "0" ]; then die "running automake"; fi
-echo "done"
-
-echo
+exit 0
