Minor rtai-load adjustments
Signed-off-by: Alec Ari <neotheuser@ymail.com>

diff --git a/scripts/rtai-load.in b/scripts/rtai-load.in
--- a/scripts/rtai-load.in
+++ b/scripts/rtai-load.in
@@ -12,7 +12,7 @@ argument_save="/tmp/runinfo"
 
 type rtai-config >> /dev/null 2>&1 || \
 	{
-		echo "${CMDNAME} cannot find rtai-config" ; exit 1 ;
+		echo "rtai-load: cannot find rtai-config" ; exit 1 ;
 	}
 
 MODULEDIR=$(rtai-config --module-dir)
@@ -33,8 +33,8 @@ while [[ "${#}" -gt "0" ]] ; do
 				}
 			done
 			echo "RTAI successfully unloaded."
-			echo "Removing /tmp/runinfo..."
-			rm -f /tmp/runinfo
+			echo "Removing ${argument_save}..."
+			rm -f "${argument_save}"
 			echo "Done."
 			exit 0
 			;;
